package com.override.game.minigames;

import javafx.scene.canvas.GraphicsContext;
import javafx.scene.image.Image;
import javafx.scene.image.PixelReader;
import javafx.scene.image.WritableImage;
import javafx.scene.paint.Color;

import java.util.HashMap;
import java.util.Map;

/**
 * Loads and caches all Kernel Panic sprite assets from
 * {@code /images/kernel-panic/}. Provides frame-slicing for sprite strips
 * and convenience draw methods for {@link KernelPanicGame}.
 *
 * <p>The PNGs were generated by an AI at a single high resolution (~1408×768),
 * so the prompt-specified "pixel" frame sizes (e.g. 16×16, 32×32) are scaled
 * up ~44–48× in the actual images. {@link #subdivide} calculates the true
 * per-frame pixel size on the actual image so we can still slice correctly.
 *
 * <p>All assets are loaded lazily on first access via
 * {@link Class#getResourceAsStream} so they work inside a JAR.
 */
public final class KernelPanicAssets {

    // =========================================================================
    //  Tunable sprite-sheet config
    //  (Prompt-spec frame sizes — the actual PNG is much larger; subdivide()
    //   computes the real pixel size automatically.)
    // =========================================================================

    /** Promised "pixel- art" frame sizes from the prompt kit. */
    private static final int PROMPT_FRAME_W = 16;
    private static final int PROMPT_FRAME_H = 16;

    // Mapping of logical prompt-frame dimensions → how many frames per strip
    // (keyed by the image key listed below).
    private record SheetLayout(int cols, int rows, int promptW, int promptH) {}

    private static final Map<String, SheetLayout> LAYOUTS = Map.ofEntries(
        Map.entry("terminal cursor",               new SheetLayout(1, 1, 32, 32)),
        Map.entry("glich token sprite",             new SheetLayout(4, 1, 16, 16)),
        Map.entry("individual glitch token",        new SheetLayout(1, 4, 24, 24)),
        Map.entry("fix ammo",                       new SheetLayout(4, 1, 16, 16)),
        Map.entry("boss enemy",                     new SheetLayout(1, 1, 48, 48)),
        Map.entry("boss hp indicator",              new SheetLayout(6, 1, 48, 8)),
        Map.entry("exploaion effect",               new SheetLayout(5, 1, 16, 16)),
        Map.entry("token death",                    new SheetLayout(4, 1, 16, 16)),
        Map.entry("emp shockwave",                  new SheetLayout(5, 1, 64, 64)),
        Map.entry("screen glitch",                  new SheetLayout(3, 1, 256, 256)),
        Map.entry("playfield bg",                   new SheetLayout(1, 1, 256, 256)),
        Map.entry("lane dibider ui element",        new SheetLayout(1, 1, 32, 256)),
        Map.entry("crt bazel",                      new SheetLayout(1, 1, 320, 240)),
        Map.entry("game over",                      new SheetLayout(1, 1, 320, 240)),
        Map.entry("hud icon set",                   new SheetLayout(4, 1, 16, 16)),
        Map.entry("numeric digit font sheet",       new SheetLayout(10, 1, 8, 16)),
        Map.entry("astro assistant button state",   new SheetLayout(2, 1, 32, 32)),
        Map.entry("combo multiplier badge",         new SheetLayout(4, 1, 24, 16)),
        Map.entry("status stamps",                  new SheetLayout(2, 1, 64, 16)),
        Map.entry("life heart icon states",         new SheetLayout(3, 1, 16, 16)),
        Map.entry("wavealert banner",               new SheetLayout(1, 1, 128, 32)),
        Map.entry("boot sequence title card",       new SheetLayout(1, 1, 128, 32)),
        Map.entry("astra interference overlay",     new SheetLayout(1, 1, 256, 256)),
        Map.entry("quantum particle effect",        new SheetLayout(4, 1, 8, 8)),
        Map.entry("miss feedback",                  new SheetLayout(1, 1, 512, 512))
    );

    private static final Map<String, Image> cache = new HashMap<>();

    // =========================================================================
    //  Public accessors
    // =========================================================================

    /** Preload every asset into the cache. Safe to call multiple times. */
    public static void preload() {
        for (String k : LAYOUTS.keySet()) get(k);
    }

    /** Load (or return cached) full image for the given asset key. */
    public static Image get(String key) {
        return cache.computeIfAbsent(key, k -> {
            var url = KernelPanicAssets.class.getResourceAsStream("/images/kernel-panic/" + k + ".png");
            if (url == null) throw new RuntimeException("Missing asset: /images/kernel-panic/" + k + ".png");
            return new Image(url);
        });
    }

    // =========================================================================
    //  Sprite-sheet slicing
    // =========================================================================

    /**
     * Returns a single frame from a sprite sheet. Frame indices are 0-based
     * and advance left-to-right, top-to-bottom.
     */
    public static Image frame(String key, int index) {
        Image sheet = get(key);
        SheetLayout lay = LAYOUTS.get(key);
        if (lay == null) return sheet;

        int total = lay.cols * lay.rows;
        if (total <= 1) return sheet;

        int col = index % lay.cols;
        int row = index / lay.cols;

        double fw = sheet.getWidth() / (double) lay.cols;
        double fh = sheet.getHeight() / (double) lay.rows;

        // Read the sub-image from the actual raster at pixel boundaries
        int px = (int) Math.round(col * fw);
        int py = (int) Math.round(row * fh);
        int pw = (int) Math.round(fw);
        int ph = (int) Math.round(fh);

        PixelReader reader = sheet.getPixelReader();
        if (reader == null) return sheet;

        WritableImage sub = new WritableImage(reader, px, py, pw, ph);
        return sub;
    }

    // =========================================================================
    //  Draw helpers — one per game-system that should use sprites
    // =========================================================================
    //  Each method has a clear "what to tweak if the frame doesn't match" note.
    //  All drawing is relative to the 480×640 game canvas.
    // =========================================================================

    // ----- Playfield ----------------------------------------------------------

    /** Draw the playfield background, scaled to fill {@code w×h}. */
    public static void drawBackground(GraphicsContext g, double w, double h) {
        g.drawImage(get("playfield bg"), 0, 0, w, h);
    }

    /**
     * Draw lane dividers from the tall divider strip.
     * Tweak: {@code divWidth} controls how many pixels of the strip are drawn.
     */
    public static void drawLaneDividers(GraphicsContext g, int lanes, double laneW, double h) {
        Image sheet = get("lane dibider ui element");
        double srcW = Math.min(sheet.getWidth(), laneW * 0.05); // ~6px slice
        for (int i = 1; i < lanes; i++) {
            double dx = i * laneW - srcW / 2;
            g.drawImage(sheet, 0, 0, srcW, sheet.getHeight(), dx, 0, srcW, h);
        }
    }

    // ----- Tokens (procedural fallback — sprite sheet slicing TBD) ------------

    /** Draw a glitch token using the procedural style (fast, reliable). */
    public static void drawTokenProcedural(GraphicsContext g,
                                            Color fill, Color bg,
                                            String glyph, boolean bold,
                                            double cx, double cy, double size,
                                            double alpha, double jitterX,
                                            boolean flicker, boolean eqGlow,
                                            Color glowColor) {
        double left = cx - size / 2 + jitterX;
        double top  = cy - size / 2;

        if (eqGlow) {
            g.setGlobalAlpha(0.35 * alpha);
            g.setFill(glowColor);
            g.fillRect(left - 4, top - 4, size + 8, size + 8);
        }

        g.setGlobalAlpha(alpha);
        g.setFill(bg);
        g.fillRect(left, top, size, size);
        g.setStroke(fill);
        g.setLineWidth(2);
        g.strokeRect(left, top, size, size);

        g.setFill(fill);
        g.setFont(javafx.scene.text.Font.font("Monospaced",
                bold ? javafx.scene.text.FontWeight.BOLD : javafx.scene.text.FontWeight.NORMAL,
                size <= 32 ? 16 : 30));
        g.setTextAlign(javafx.scene.text.TextAlignment.CENTER);
        g.setTextBaseline(javafx.geometry.VPos.CENTER);
        g.fillText(glyph, cx + jitterX, cy);
        g.setGlobalAlpha(1);
    }

    // ----- HUD ---------------------------------------------------------------

    /**
     * Draw a score integer using digit-font frames.
     * Tweak: {@code digW} is the frame width on the actual PNG.
     */
    public static void drawScore(GraphicsContext g, int score,
                                  double x, double y, double scale) {
        Image digits = get("numeric digit font sheet");
        String s = Integer.toString(score);
        double digW = digits.getWidth() / 10.0;
        double digH = digits.getHeight();
        double sw = digW * scale;
        double sh = digH * scale;
        double curX = x;
        for (int i = 0; i < s.length(); i++) {
            int d = s.charAt(i) - '0';
            g.drawImage(digits, d * digW, 0, digW, digH, curX, y, sw, sh);
            curX += sw;
        }
    }

    /**
     * Draw life hearts (3-state: full / empty / lost).
     * Tweak: frame count is 3 (change {@code states} if different).
     */
    public static void drawLives(GraphicsContext g, int lives, int maxLives,
                                  double x, double y, double size) {
        Image sheet = get("life heart icon states");
        int states = 3;
        double fw = sheet.getWidth() / states;
        double fh = sheet.getHeight();
        double curX = x;
        for (int i = 0; i < maxLives; i++) {
            int state = i < lives ? 0 : (i == lives ? 1 : 2);
            g.drawImage(sheet, state * fw, 0, fw, fh, curX, y, size, size);
            curX += size + 4;
        }
    }

    /** Draw a single frame from the combo multiplier badge strip. */
    public static void drawComboBadge(GraphicsContext g, int combo,
                                       double cx, double cy, double scale) {
        Image sheet = get("combo multiplier badge");
        double fw = sheet.getWidth() / 4.0;
        double fh = sheet.getHeight();

        int idx = combo >= 25 ? 3 : combo >= 10 ? 2 : combo >= 5 ? 1 : 0;
        double w = fw * scale;
        double h = fh * scale;
        g.drawImage(sheet, idx * fw, 0, fw, fh, cx - w / 2, cy - h / 2, w, h);
    }

    /** Draw the status stamp: 0 = ASSISTED, 1 = UNASSISTED. */
    public static void drawStatusStamp(GraphicsContext g, boolean assisted,
                                        double cx, double cy, double scale) {
        Image sheet = get("status stamps");
        double fw = sheet.getWidth() / 2.0;
        double fh = sheet.getHeight();
        int idx = assisted ? 0 : 1;
        double w = fw * scale;
        double h = fh * scale;
        g.drawImage(sheet, idx * fw, 0, fw, fh, cx - w / 2, cy - h / 2, w, h);
    }

    /** Draw the wave-alert banner. */
    public static void drawWaveAlert(GraphicsContext g, int wave, boolean boss,
                                      double canvasW, double canvasH) {
        g.drawImage(get("wavealert banner"), 0, 0, canvasW, canvasH);
    }

    // ----- Overlays ----------------------------------------------------------

    /** Full CRT bezel overlay, stretched to canvas. */
    public static void drawCrtBezel(GraphicsContext g, double w, double h) {
        g.drawImage(get("crt bazel"), 0, 0, w, h);
    }

    /** Screen glitch overlay at given alpha. */
    public static void drawScreenGlitch(GraphicsContext g, double w, double h, double alpha) {
        g.setGlobalAlpha(alpha);
        g.drawImage(get("screen glitch"), 0, 0, w, h);
        g.setGlobalAlpha(1);
    }

    /** Astra EMP interference overlay at given alpha. */
    public static void drawAstraInterference(GraphicsContext g, double w, double h, double alpha) {
        g.setGlobalAlpha(alpha);
        g.drawImage(get("astra interference overlay"), 0, 0, w, h);
        g.setGlobalAlpha(1);
    }

    /** Game-over screen image, stretched to canvas. */
    public static void drawGameOver(GraphicsContext g, double w, double h) {
        g.drawImage(get("game over"), 0, 0, w, h);
    }

    /** Boot sequence title card. */
    public static void drawBootTitle(GraphicsContext g, double w, double h) {
        g.drawImage(get("boot sequence title card"), 0, 0, w, h);
    }

    // ----- Effects -----------------------------------------------------------

    /** Draw the miss feedback icon centred at (cx, cy). */
    public static void drawMissFeedback(GraphicsContext g, double cx, double cy, double size) {
        g.drawImage(get("miss feedback"), cx - size / 2, cy - size / 2, size, size);
    }

    /** Draw a boss HP indicator bar at the given fill ratio. */
    public static void drawBossHpBar(GraphicsContext g, double cx, double cy,
                                      double ratio, double width, double height) {
        Image bar = get("boss hp indicator");
        double srcW = bar.getWidth() * Math.min(1, Math.max(0, ratio));
        g.drawImage(bar, 0, 0, srcW, bar.getHeight(), cx - width / 2, cy - height / 2, srcW / bar.getWidth() * width, height);
    }
}
